# Generated by Django 5.1.7 on 2025-03-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado_ldd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='certificados_generados/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='certificado_ldd.clientesbia')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
