# Generated by Django 5.1.7 on 2025-04-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesBia',
            fields=[
                ('entidad_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cartera', models.CharField(blank=True, max_length=50, null=True)),
                ('legajo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('deuda_o', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('f_caida_real', models.DateField(blank=True, null=True)),
                ('deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('f_caida', models.DateField(blank=True, null=True)),
                ('estado_leg', models.CharField(blank=True, max_length=50, null=True)),
                ('promesa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('convenio', models.CharField(blank=True, max_length=10, null=True)),
                ('f_operacion', models.DateField(blank=True, null=True)),
                ('estado_conv', models.CharField(blank=True, max_length=20, null=True)),
                ('operador', models.CharField(blank=True, max_length=255, null=True)),
                ('ult_tarea', models.CharField(blank=True, max_length=50, null=True)),
                ('ult_tarea2', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vto', models.DateField(blank=True, null=True)),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_deudor', models.CharField(blank=True, max_length=50, null=True)),
                ('id_operacion', models.IntegerField(blank=True, null=True)),
                ('nro_operacion', models.IntegerField(blank=True, null=True)),
                ('idpagounico', models.CharField(blank=True, max_length=100, null=True)),
                ('promo', models.CharField(blank=True, max_length=50, null=True)),
                ('segmentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('negocio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clientes_bia',
                'managed': False,
            },
        ),
    ]
