# Generated by Django 5.1.7 on 2025-03-17 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=11, unique=True)),
                ('debt_cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='certificados/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificado.client')),
            ],
        ),
    ]
