# Generated by Django 5.1.7 on 2025-03-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_clientesbia_alter_certificate_client_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='certificado.clientesbia'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(upload_to='certificados_generados/'),
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='certificate',
        ),
    ]
